/**
 * SequenceSearch Component  –  frontend/src/components/SequenceSearch.jsx
 */

import React, { useState, useCallback, useRef } from 'react';
import { Link } from 'gatsby';
import config from '../config';
import { addJobId } from '../utils/session';
import SearchHistory from './SearchHistory';
import ExampleCards from './ExampleCards';

const EXAMPLE_SEQUENCES = {
  isPETase: `>IsPETase (WP_054022242.1)
MNFPRASRLMQAAVLGGLMAVSAAATAQTNPYARGPNPTAASLEASAGPFTVRSFTVSRPSGYGAGTVYYPTNAGGTVGAIAIVPGYTARQSSIKWWGPRLASHGFVVITIDTNSTLDQPSSRSSQQMAALRQVASLNGTSSSPIYGKVDTARMGVMGWSMGGGGSLISAANNPSLKAAAPQAPWDSSTNFSSVTVPTLIFACENDSIAPVNSSALPIYDSMSRNAKQFLEINGGSHSCANSGNSNQALIGKKGVAWMKRFMDNDTRYSTFACENPNSTRVSDFRTANCS`
};

const GITHUB_REPO = 'ababaian/petadex.io';

function buildBugReportUrl(message, jobId) {
  const title = encodeURIComponent(`[Bug] Search error: ${message}`);
  const body  = encodeURIComponent(
    `## Automatic error report\n\n` +
    `**Job ID:** \`${jobId || 'N/A'}\`\n` +
    `**URL:** ${typeof window !== 'undefined' ? window.location.href : 'N/A'}\n` +
    `**Timestamp:** ${new Date().toISOString()}\n` +
    `**Error:** ${message}\n\n` +
    `*Auto-generated by PETadex error handler*`
  );
  return `https://github.com/${GITHUB_REPO}/issues/new?title=${title}&body=${body}&labels=bug`;
}

const SequenceSearch = () => {
  // ── Read initial state from URL params (?seq=...&n=50) ───────────────────
  const urlParams     = typeof window !== 'undefined' ? new URLSearchParams(window.location.search) : new URLSearchParams();
  const seqFromUrl    = urlParams.get('seq') || '>';
  const nFromUrl      = parseInt(urlParams.get('n'), 10) || 50;

  const [sequence,   setSequence]   = useState(seqFromUrl);
  const [maxResults, setMaxResults] = useState(nFromUrl);
  const [jobId,      setJobId]      = useState(null);
  const [status,     setStatus]     = useState('idle');
  const [results,    setResults]    = useState(null);
  const [error,      setError]      = useState(null); // { message, jobId, bugUrl } | null
  const [metadata,   setMetadata]   = useState(null);
  const [newSearchCount, setNewSearchCount] = useState(0);
  const pollIntervalRef = useRef(null);

  const searchApiUrl = process.env.GATSBY_SEARCH_API_URL || config.apiUrl;

  const cleanupPolling = useCallback(() => {
    if (pollIntervalRef.current) {
      clearInterval(pollIntervalRef.current);
      pollIntervalRef.current = null;
    }
  }, []);

  const failWithError = useCallback((message, id) => {
    cleanupPolling();
    setStatus('error');
    setError({ message, jobId: id, bugUrl: buildBugReportUrl(message, id) });
  }, [cleanupPolling]);

  // ── Sync search params to URL ─────────────────────────────────────────────
  const updateUrl = useCallback((seq, n, jobId) => {
    if (typeof window === 'undefined') return;
    const params = new URLSearchParams();
    const clean  = seq.split('\n').filter(l => !l.trim().startsWith('>')).join('').replace(/[\s\r]/g, '').toUpperCase();
    if (clean) params.set('seq', clean);
    if (n !== 50) params.set('n', n);
    if (jobId) params.set('job', jobId);
    const newUrl = `${window.location.pathname}?${params.toString()}`;
    window.history.replaceState(null, '', newUrl);
  }, []);

  const pollResults = useCallback(async (id, cleanSequence) => {
    try {
      const response = await fetch(`${searchApiUrl}/search/results/${id}`);
      const data     = await response.json();

      if (!response.ok) {
        failWithError(data.error || `Server error ${response.status}`, id);
        return;
      }

      if (data.status === 'completed') {
        cleanupPolling();
        addJobId(data.job_id);
        setStatus('completed');
        setResults(data.results);
        setMetadata(data.metadata);
        setNewSearchCount(n => n + 1);
        updateUrl(cleanSequence, maxResults, data.job_id || id);
      } else if (data.status === 'failed') {
        failWithError(data.error || 'Search failed', id);
      }
      // status === 'processing' -> keep polling
    } catch (err) {
      failWithError('Failed to fetch results. Please try again.', id);
    }
  }, [searchApiUrl, cleanupPolling, failWithError, maxResults, updateUrl]);

  // ── Submit ────────────────────────────────────────────────────────────────
  const submitSearch = async () => {
    const cleanSequence = sequence
      .split('\n')
      .filter(line => !line.trim().startsWith('>'))
      .join('')
      .replace(/[\s\r]/g, '')
      .toUpperCase();

    if (!cleanSequence || cleanSequence.length < 10) {
      setError({ message: 'Please enter a valid protein sequence (at least 10 amino acids)', jobId: null, bugUrl: null });
      return;
    }

    setError(null);
    setResults(null);
    setMetadata(null);
    setStatus('submitting');
    cleanupPolling();

    try {
      const response = await fetch(`${searchApiUrl}/search`, {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ sequence: cleanSequence, max_results: maxResults }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || `Server error ${response.status}`);
      }

      // Cache hit — results returned immediately
      if (data.status === 'completed') {
        const id = data.session_id || data.job_id;
        setJobId(id);
        addJobId(data.job_id);
        setStatus('completed');
        setResults(data.results);
        setMetadata(data.metadata);
        setNewSearchCount(n => n + 1);
        updateUrl(cleanSequence, maxResults, id);
        return;
      }

      // Backend returns session_id as the polling key
      const pollId = data.session_id || data.job_id;
      setJobId(pollId);
      addJobId(data.job_id);
      setStatus('polling');

      pollIntervalRef.current = setInterval(() => pollResults(pollId, cleanSequence), 3000);
      setTimeout(() => pollResults(pollId, cleanSequence), 500);

    } catch (err) {
      failWithError(err.message || 'Failed to submit search. Please try again.', null);
    }
  };

  const loadExample = (name) => { setSequence(EXAMPLE_SEQUENCES[name]); setError(null); };

  const handleReset = () => {
    cleanupPolling();
    setSequence('>');
    setJobId(null);
    setStatus('idle');
    setResults(null);
    setError(null);
    setMetadata(null);
    if (typeof window !== 'undefined') {
      window.history.replaceState(null, '', window.location.pathname);
    }
  };

  const loadPastSearch = useCallback(async (pastJobId) => {
    setError(null);
    setStatus('polling');
    setJobId(pastJobId);

    try {
      const response = await fetch(`${searchApiUrl}/search/results/${pastJobId}`);
      const data     = await response.json();

      if (!response.ok) {
        failWithError(data.error || `Server error ${response.status}`, pastJobId);
        return;
      }

      if (data.status === 'completed') {
        setStatus('completed');
        setResults(data.results);
        setMetadata(data.metadata);
      } else if (data.status === 'failed') {
        failWithError(data.error || 'Search failed', pastJobId);
      } else if (data.status === 'not_found') {
        failWithError('Search results not found or expired.', pastJobId);
      } else if (data.status === 'processing') {
        pollIntervalRef.current = setInterval(() => pollResults(pastJobId), 3000);
      } else {
        failWithError('Unable to load search results.', pastJobId);
      }
    } catch (err) {
      failWithError('Failed to load past search results.', pastJobId);
    }
  }, [searchApiUrl, pollResults, failWithError]);

  // ── Load cached results on mount if ?job= param is in URL ───────────────
  React.useEffect(() => {
    const jobFromUrl = urlParams.get('job');
    if (jobFromUrl) loadPastSearch(jobFromUrl);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  React.useEffect(() => () => cleanupPolling(), [cleanupPolling]);

  return (
    <div className="sequence-search">
      <style>{`
        .sequence-search { width: 100%; }
        .input-section { margin-bottom: 1.5rem; }
        .sequence-textarea {
          width: 100%; min-height: 150px; padding: 0.75rem;
          font-family: monospace; font-size: 0.9rem;
          border: 1px solid #ddd; border-radius: 4px; resize: vertical;
          box-sizing: border-box;
        }
        .sequence-textarea:focus { outline: none; border-color: #007bff; box-shadow: 0 0 0 2px rgba(0,123,255,0.1); }
        .example-buttons { margin-top: 0.5rem; font-size: 0.85rem; }
        .example-buttons button { background: none; border: none; color: #007bff; cursor: pointer; padding: 0; margin-right: 1rem; }
        .example-buttons button:hover { text-decoration: underline; }
        .options-row { display: flex; align-items: center; gap: 1rem; margin-bottom: 1rem; margin-top: 0.75rem; }
        .options-row label { display: flex; align-items: center; gap: 0.5rem; }
        .submit-btn { background: #007bff; color: #fff; border: none; padding: 0.6rem 1.5rem; border-radius: 4px; font-size: 1rem; cursor: pointer; }
        .submit-btn:hover:not(:disabled) { background: #0056b3; }
        .submit-btn:disabled { background: #6c757d; cursor: not-allowed; }
        .reset-btn { margin-left: 0.75rem; background: none; border: 1px solid #ccc; padding: 0.6rem 1.2rem; border-radius: 4px; cursor: pointer; }
        .reset-btn:hover { background: #f8f9fa; }
        .status-message { margin-top: 1rem; padding: 0.75rem 1rem; border-radius: 4px; }
        .status-message.processing { background: #e8f4fd; color: #0c5460; display: flex; align-items: center; gap: 0.5rem; flex-wrap: wrap; }
        .status-message.error { background: #fde8e8; color: #721c24; }
        .error-bug-link { display: inline-flex; align-items: center; gap: 0.3rem; margin-top: 0.4rem; font-size: 0.85rem; color: #c0392b; font-weight: 500; }
        .error-bug-link:hover { text-decoration: underline; }
        @keyframes spin { to { transform: rotate(360deg); } }
        .spinner { display: inline-block; width: 1rem; height: 1rem; flex-shrink: 0; border: 2px solid #bee5eb; border-top-color: #0c5460; border-radius: 50%; animation: spin 0.8s linear infinite; }
        .results-section { margin-top: 1.5rem; }
        .results-header { margin-bottom: 1rem; }
        .results-header h3 { margin: 0 0 0.25rem 0; }
        .results-meta { font-size: 0.85rem; color: #666; }
        .results-table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
        .results-table th { background: #f8f9fa; text-align: left; padding: 0.5rem; border-bottom: 2px solid #dee2e6; }
        .results-table td { padding: 0.5rem; border-bottom: 1px solid #dee2e6; }
        .results-table tr:hover td { background: #f8f9fa; }
        .accession-link { color: #007bff; text-decoration: none; }
        .accession-link:hover { text-decoration: underline; }
        .identity-bar { display: inline-block; height: 6px; background: #28a745; border-radius: 3px; margin-right: 4px; vertical-align: middle; }
        .no-results { padding: 2rem; text-align: center; color: #666; }
      `}</style>

      <ExampleCards onSelectExample={loadPastSearch} disabled={status === 'submitting' || status === 'polling'} />

      <div className="input-section">
        <textarea
          className="sequence-textarea"
          placeholder=">Header (optional)&#10;PASTE_SEQUENCE_HERE..."
          value={sequence}
          onChange={(e) => {
            const val = e.target.value;
            setSequence(val.startsWith('>') ? val : `>${val}`);
          }}
          disabled={status === 'submitting' || status === 'polling'}
        />
        <div className="example-buttons">
          <span>Load example: </span>
          <button onClick={() => loadExample('isPETase')}>IsPETase</button>
        </div>
      </div>

      <div className="options-row">
        <label>
          Max results:
          <select
            value={maxResults}
            onChange={(e) => setMaxResults(parseInt(e.target.value, 10))}
            disabled={status === 'submitting' || status === 'polling'}
          >
            {[10, 25, 50, 100, 250].map(n => <option key={n} value={n}>{n}</option>)}
          </select>
        </label>
      </div>

      <div>
        <button
          className="submit-btn"
          onClick={submitSearch}
          disabled={status === 'submitting' || status === 'polling' || sequence.replace(/^>.*\n?/gm, '').trim().length < 10}
        >
          {status === 'submitting' ? 'Submitting...' : status === 'polling' ? 'Searching...' : 'Search'}
        </button>
        {(status === 'completed' || status === 'error' || results) && (
          <button className="reset-btn" onClick={handleReset}>New Search</button>
        )}
      </div>

      {status === 'polling' && (
        <div className="status-message processing">
          <span className="spinner" />
          Searching database... This may take a few seconds.
          {jobId && <span style={{ marginLeft: '1rem', fontSize: '0.8rem', color: '#555' }}>Job ID: {jobId}</span>}
        </div>
      )}

      {error && (
        <div className="status-message error">
          <div>{error.message}</div>
          {error.bugUrl && (
            <a className="error-bug-link" href={error.bugUrl} target="_blank" rel="noopener noreferrer">
              🐛 Report this bug on GitHub
            </a>
          )}
        </div>
      )}

      {status === 'completed' && results && (
        <div className="results-section">
          <div className="results-header">
            <h3>Search Results</h3>
            {metadata && (
              <div className="results-meta">
                {[
                  metadata.query_length   && `Query length: ${metadata.query_length} aa`,
                  metadata.database_size  && `Database size: ${metadata.database_size.toLocaleString()} sequences`,
                  metadata.search_time_ms && `Search time: ${metadata.search_time_ms}ms`,
                ].filter(Boolean).join(' | ')}
              </div>
            )}
          </div>

          {results.length > 0 ? (
            <table className="results-table">
              <thead>
                <tr>
                  <th>#</th><th>Accession</th><th>Name</th><th>Organism</th>
                  <th>Identity</th><th>E-value</th><th>Coverage</th>
                </tr>
              </thead>
              <tbody>
                {results.map((hit) => (
                  <tr key={hit.accession}>
                    <td>{hit.rank}</td>
                    <td><Link to={`/sequence/${hit.accession}`} className="accession-link">{hit.accession}</Link></td>
                    <td>{hit.name || '-'}</td>
                    <td><em>{hit.organism || '-'}</em></td>
                    <td>
                      <span className="identity-bar" style={{ width: `${Math.min(hit.identity ?? 0, 100)}px` }} />
                      {hit.identity?.toFixed(1) ?? '-'}%
                    </td>
                    <td>{hit.evalue === 0 ? '0' : hit.evalue?.toExponential(1) ?? '-'}</td>
                    <td>{hit.query_coverage ?? '-'}%</td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <div className="no-results">
              <p>No similar sequences found in the database.</p>
              <p>Try adjusting your search parameters or using a different sequence.</p>
            </div>
          )}
        </div>
      )}

      <SearchHistory
        onSelectSearch={loadPastSearch}
        currentJobId={status === 'completed' ? jobId : null}
        newSearchCount={newSearchCount}
      />
    </div>
  );
};

export default SequenceSearch;
