/**
 * Search Routes  –  backend/src/routes/search.js
 *
 * Lambda interface (petadex-mmseqs2-search):
 *   Input:  { sessionId, sequence, max_results }
 *   Output: { job_id, s3_key }
 *   S3:     results/{sessionId}/{job_id}.json   (subfolder per session)
 *           results/{sessionId}.index           (contains job_id, written by Lambda)
 *
 * Flow:
 *   POST /api/search
 *     1. Check results/{sessionId}.index — return cached results immediately if found
 *     2. Fire Lambda async (Event) — returns 202 immediately
 *     3. Client polls GET /api/search/results/{sessionId}
 *
 *   GET /api/search/results/:sessionId
 *     1. Check index file — return completed results if found
 *     2. Return processing if no index yet
 */

/**
 *    User A searches "MNFP..."
 *            ↓
 *    session_id = MD5("MNFP...") = "a1b2c3..."
 *    Lambda runs → writes results/a1b2c3....index
 *                            results/a1b2c3.../550e8400-....json
 *
 *    User B searches "MNFP..." (same sequence)
 *            ↓
 *    session_id = MD5("MNFP...") = "a1b2c3..."  ← identical
 *            ↓
 *    resolveFromIndex finds results/a1b2c3....index ← cache hit
 *    Returns immediately, Lambda never invoked
 */

import { Router } from 'express';
import Joi from 'joi';
import { createHash } from 'crypto';
import { LambdaClient, InvokeCommand } from '@aws-sdk/client-lambda';
import { S3Client, GetObjectCommand, ListObjectsV2Command, HeadObjectCommand, PutObjectCommand } from '@aws-sdk/client-s3';
import { pool } from '../db.js';

const router = Router();

let lambdaClient = null;
let s3Client = null;

const AWS_REGION = process.env.AWS_REGION || 'us-east-1';
const MMSEQS2_LAMBDA_NAME = process.env.MMSEQS2_LAMBDA_NAME || 'petadex-mmseqs2-search';
const RESULTS_BUCKET = process.env.RESULTS_BUCKET || 'petadex';
const RESULTS_PREFIX = process.env.RESULTS_PREFIX || 'results';
const GITHUB_REPO = process.env.GITHUB_REPO || 'ababaian/petadex.io';

function getLambdaClient() {
  if (!lambdaClient) lambdaClient = new LambdaClient({ region: AWS_REGION });
  return lambdaClient;
}
function getS3Client() {
  if (!s3Client) s3Client = new S3Client({ region: AWS_REGION });
  return s3Client;
}

async function streamToString(stream) {
  const chunks = [];
  for await (const chunk of stream) chunks.push(chunk);
  return Buffer.concat(chunks).toString('utf8');
}

function makeSessionId(cleanSequence, maxResults) {
  return createHash('md5')
    .update(`${cleanSequence}:${maxResults}`)
    .digest('hex');
}

function buildBugReportUrl(message, jobId) {
  const title = encodeURIComponent(`[Bug] Search error: ${message}`);
  const body = encodeURIComponent(
    `## Automatic error report\n\n` +
    `**Job ID:** \`${jobId || 'N/A'}\`\n` +
    `**Timestamp:** ${new Date().toISOString()}\n` +
    `**Error:** ${message}\n\n` +
    `*Auto-generated by PETadex error handler*`
  );
  return `https://github.com/${GITHUB_REPO}/issues/new?title=${title}&body=${body}&labels=bug`;
}

function sendError(res, statusCode, message, jobId = null) {
  const wantsHtml = (res.req.headers.accept || '').includes('text/html');
  const bugUrl = buildBugReportUrl(message, jobId);

  if (wantsHtml) {
    return res.status(statusCode).type('html').send(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>PETadex - Search Error ${statusCode}</title>
  <style>
    body { font-family:system-ui,sans-serif; max-width:640px; margin:4rem auto; padding:0 1rem; }
    h1   { color:#c0392b; }
    pre  { background:#f4f4f4; padding:1rem; border-radius:4px; }
    .btn { display:inline-block; margin-top:1.5rem; padding:.6rem 1.2rem;
           background:#24292f; color:#fff; border-radius:6px; text-decoration:none; }
  </style>
</head>
<body>
  <h1>Search Error ${statusCode}</h1>
  <p>${message}</p>
  ${jobId ? `<pre>Job ID: ${jobId}</pre>` : ''}
  <a class="btn" href="${bugUrl}" target="_blank" rel="noopener noreferrer">Report this bug on GitHub</a>
</body>
</html>`);
  }

  const payload = { error: message, bug_report_url: bugUrl };
  if (jobId) payload.job_id = jobId;
  return res.status(statusCode).json(payload);
}

function transformResults(rawResults, queryLength) {
  return (rawResults || []).map((hit, index) => ({
    rank: index + 1,
    accession: hit.target_id,
    target_id: hit.target_id,
    name: hit.target_name || hit.metadata?.definition || null,
    organism: hit.organism || hit.metadata?.organism || null,
    taxonomy: hit.taxonomy || hit.metadata?.taxonomy || null,
    percent_identity: hit.percent_identity,
    identity: hit.percent_identity,
    evalue: hit.evalue,
    bitscore: hit.bitscore,
    query_coverage: queryLength && hit.query_end != null && hit.query_start != null
      ? Math.round(((hit.query_end - hit.query_start + 1) / queryLength) * 100)
      : null,
    alignment_length: hit.alignment_length,
    query_start: hit.query_start,
    query_end: hit.query_end,
    target_start: hit.target_start,
    target_end: hit.target_end,
  }));
}

const searchSchema = Joi.object({
  sequence: Joi.string()
    .pattern(/^>[^\n\r]+[\n\r]+[ACDEFGHIKLMNPQRSTVWY\s\n\r*-]+$/i)
    .min(10).max(10000).required()
    .messages({ 'string.pattern.base': 'Sequence must begin with a FASTA header line (e.g. >accession) followed by amino acid sequence.' }),
  max_results: Joi.number().integer().min(1).max(500).default(50),
});

const jobIdSchema = Joi.alternatives().try(
  Joi.string().pattern(/^[a-f0-9]{32}$/),                    // MD5 sessionId
  Joi.string().uuid({ version: 'uuidv4' }),                   // Lambda job_id
  Joi.string().pattern(/^regen_example_[a-zA-Z0-9_]+$/)      // example slugs
).required();

const EXAMPLE_SEARCHES = [
  {
    job_id: 'regen_example_ispetase',
    name: 'IsPETase',
    description: 'Well-characterized PETase from Ideonella sakaiensis',
    organism: 'Ideonella sakaiensis',
    query_length: 290,
  },
  {
    job_id: 'regen_example_fast_petase',
    name: 'FAST-PETase',
    description: 'Engineered variant with enhanced activity and thermostability',
    organism: 'Engineered',
    query_length: 290,
  },
  {
    job_id: 'regen_example_srr10663367',
    name: 'SRR10663367',
    description: 'Logan-discovered enzyme with activity exceeding FAST-PETase',
    organism: 'Metagenome',
    query_length: 290,
  },
];


// Check S3 in parallel for which family IDs have a phylogenetic tree file.
// Returns a Set of family IDs (numbers) that have a corresponding .nwk file.
async function checkFamilyTrees(familyIds) {
  if (!familyIds.length) return new Set();
  const client = getS3Client();
  const results = await Promise.allSettled(
    familyIds.map(id =>
      client.send(new HeadObjectCommand({
        Bucket: RESULTS_BUCKET,
        Key: `search-phylo-trees/family_${id}.nwk`
      })).then(() => id)
    )
  );
  return new Set(
    results.filter(r => r.status === 'fulfilled').map(r => r.value)
  );
}

// Batch-query DB for family/component data for a list of accessions.
// Checks enzyme_fastaa directly, then variant_dictionary as fallback.
async function enrichWithFamilyData(accessions) {
  if (!accessions.length) return {};

  const { rows } = await pool.query(
    `WITH direct AS (
       SELECT e.genbank_accession_id AS accession,
              e.enzyme_id,
              t.family,
              t.component,
              t.family_pid
       FROM enzyme_fastaa e
       LEFT JOIN enzyme_taxonomy t ON t.enzyme_id = e.enzyme_id
       WHERE e.genbank_accession_id = ANY($1)
     ),
     via_variant AS (
       SELECT v.genbank_accession_id AS accession,
              e.enzyme_id,
              t.family,
              t.component,
              t.family_pid
       FROM variant_dictionary v
       JOIN enzyme_fastaa e ON e.enzyme_id = v.enzyme_id
       LEFT JOIN enzyme_taxonomy t ON t.enzyme_id = v.enzyme_id
       WHERE v.genbank_accession_id = ANY($1)
         AND v.genbank_accession_id NOT IN (SELECT accession FROM direct)
     )
     SELECT * FROM direct
     UNION ALL
     SELECT * FROM via_variant`,
    [accessions]
  );

  // Index by accession for O(1) lookup
  const map = {};
  for (const row of rows) {
    map[row.accession] = {
      enzyme_id: row.enzyme_id,
      family: row.family,
      component: row.component,
      family_pid: row.family_pid
    };
  }
  return map;
}

// ─── Shared helper: resolve sessionId via index file ─────────────────────────
// Lambda writes results/{sessionId}.index containing the job_id after search.
// Returns completed result object or null if not ready yet.
async function resolveFromIndex(s3, sessionId) {
  const indexKey = `${RESULTS_PREFIX}/${sessionId}.index`;
  try {
    const idxResp = await s3.send(new GetObjectCommand({ Bucket: RESULTS_BUCKET, Key: indexKey }));
    const jobId = (await streamToString(idxResp.Body)).trim();
    const s3Key = `${RESULTS_PREFIX}/${sessionId}/${jobId}.json`;
    const resp = await s3.send(new GetObjectCommand({ Bucket: RESULTS_BUCKET, Key: s3Key }));
    const content = await streamToString(resp.Body);
    const data = JSON.parse(content);
    return { jobId, data };
  } catch {
    return null;
  }
}


/**
 * POST /api/search
 *
 * 1. Validate body
 * 2. MD5(sequence + max_results) = sessionId
 * 3. Check index file — return cached results immediately if found
 * 4. Fire Lambda async (Event) — returns 202 immediately
 * 5. Client polls GET /api/search/results/{sessionId}
 */
router.post('/', async (req, res, next) => {
  try {
    const { error, value } = searchSchema.validate(req.body);
    if (error) return sendError(res, 400, error.details[0].message);

    const { sequence, max_results } = value;
    const cleanSequence = sequence.replace(/^>[^\n\r]*[\n\r]+/, '').replace(/[\s\n\r]/g, '').toUpperCase();
    const sessionId = makeSessionId(cleanSequence, max_results);
    const s3 = getS3Client();

    // ── Cache lookup via index file ───────────────────────────────────────────
    const cached = await resolveFromIndex(s3, sessionId);
    if (cached) {
      console.log(`Cache hit – sessionId=${sessionId} job=${cached.jobId}`);
      return res.json({
        job_id: cached.jobId,
        session_id: sessionId,
        status: 'completed',
        cached: true,
        results: transformResults(cached.data.results, cached.data.query_length),
        metadata: {
          query_length: cached.data.query_length,
          num_results: cached.data.num_results,
          database_size: cached.data.database_size,
          search_time_ms: cached.data.search_time_ms,
          timestamp: cached.data.timestamp,
        },
      });
    }

    // ── Fire Lambda async ─────────────────────────────────────────────────────
    try {
      await getLambdaClient().send(new InvokeCommand({
        FunctionName: MMSEQS2_LAMBDA_NAME,
        InvocationType: 'Event',
        Payload: JSON.stringify({
          sessionId: sessionId,
          sequence: cleanSequence,
          max_results: max_results,
        }),
      }));
      console.log(`Lambda invoked async – sessionId=${sessionId}`);
    } catch (lambdaErr) {
      console.error('Lambda invocation failed:', lambdaErr);
      return sendError(res, 500, `Search failed: ${lambdaErr.message}`, sessionId);
    }

    return res.status(202).json({
      session_id: sessionId,
      status: 'processing',
      message: `Poll /api/search/results/${sessionId} for results.`,
    });

  } catch (err) {
    next(err);
  }
});

/**
 * GET /api/phylo-tree/:family_id
 * Serve the Newick tree file for a given enzyme family from S3.
 * Proxies the content so external viewers (e.g. icytree.org) can fetch it via CORS.
 */
router.get('/phylo-tree/:family_id', async (req, res, next) => {
  const familyId = parseInt(req.params.family_id, 10);
  if (!Number.isInteger(familyId) || familyId <= 0) {
    return res.status(400).json({ error: 'Invalid family_id' });
  }

  const key = `search-phylo-trees/family_${familyId}.nwk`;
  const client = getS3Client();

  try {
    const getCommand = new GetObjectCommand({ Bucket: RESULTS_BUCKET, Key: key });
    const response = await client.send(getCommand);
    const content = await streamToString(response.Body);

    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Content-Disposition', `inline; filename="family_${familyId}.nwk"`);
    res.send(content);
  } catch (err) {
    if (err.name === 'NoSuchKey' || err.$metadata?.httpStatusCode === 404) {
      return res.status(404).json({ error: `No phylogenetic tree found for family ${familyId}` });
    }
    next(err);
  }
});

/**
 * GET /api/search/examples
 */
router.get('/examples', (_req, res) => res.json({ examples: EXAMPLE_SEARCHES }));


/**
 * GET /api/search/results/:job_id
 *
 * MD5 sessionId or regen_example_*:
 *   - Check index file → completed if found, processing if not
 * UUID job_id:
 *   - Fetch results/{sessionId}/{job_id}.json directly (for history/shared links)
 */
router.get('/results/:job_id', async (req, res, next) => {
  try {
    const { error, value: jobId } = jobIdSchema.validate(req.params.job_id);
    if (error) return sendError(res, 400, 'Invalid job_id format.');

    const s3 = getS3Client();

    // MD5 sessionId or regen_example_* — check index file
    if (/^[a-f0-9]{32}$/.test(jobId) || /^regen_example_/.test(jobId)) {
      const result = await resolveFromIndex(s3, jobId);

      if (!result) {
        // Index not written yet — Lambda still running
        return res.json({ status: 'processing', session_id: jobId });
      }

      const transformedResults = transformResults(result.data.results, result.data.query_length)

      // Enrich with family/component data from DB, then check S3 for tree files
      try {
        const accessions = transformedResults.map(r => r.accession).filter(Boolean);
        const familyMap = await enrichWithFamilyData(accessions);
        for (const hit of transformedResults) {
          const info = familyMap[hit.accession];
          hit.enzyme_id = info?.enzyme_id ?? null;
          hit.family = info?.family ?? null;
          hit.component = info?.component ?? null;
          hit.family_pid = info?.family_pid ?? null;
        }

        const uniqueFamilyIds = [...new Set(
          transformedResults.map(r => r.family).filter(f => f != null)
        )];
        const familiesWithTrees = await checkFamilyTrees(uniqueFamilyIds);
        for (const hit of transformedResults) {
          hit.has_tree = hit.family != null && familiesWithTrees.has(hit.family);
        }
      } catch (dbErr) {
        console.error('Family enrichment failed (non-fatal):', dbErr);
      }

      return res.json({
        status: 'completed',
        job_id: result.jobId,
        session_id: jobId,
        cached: true,
        results: transformedResults,
        metadata: {
          query_length: result.data.query_length,
          num_results: result.data.num_results,
          database_size: result.data.database_size,
          search_time_ms: result.data.search_time_ms,
          timestamp: result.data.timestamp,
        },
      });
    }

    return res.status(404).json({ status: 'not_found', job_id: jobId, error: 'Job not found.' });

  } catch (err) {
    next(err);
  }
});


/**
 * GET /api/search/history
 * Lists result files under results/{sessionId}/ subfolders
 */
router.get('/history', async (req, res, next) => {
  try {
    const limit = Math.min(parseInt(req.query.limit, 10) || 50, 100);
    const jobIdsParam = req.query.job_ids;
    const filterIds = jobIdsParam ? jobIdsParam.split(',').filter(Boolean) : null;

    const s3 = getS3Client();
    const list = await s3.send(new ListObjectsV2Command({
      Bucket: RESULTS_BUCKET,
      Prefix: `${RESULTS_PREFIX}/`,
      MaxKeys: limit * 4,
    }));

    // Results are at results/{sessionId}/{job_id}.json
    const resultObjects = (list.Contents || []).filter(obj => {
      if (!obj.Key.endsWith('.json')) return false;
      const parts = obj.Key.split('/');
      if (parts.length < 3) return false;  // must be in a subfolder
      const jobId = parts[parts.length - 1].replace('.json', '');
      if (jobId.startsWith('example_')) return false;
      return filterIds ? filterIds.includes(jobId) : true;
    });


    const searches = await Promise.all(
      resultObjects.slice(0, limit).map(async obj => {
        const parts = obj.Key.split('/');
        const jobId = parts[parts.length - 1].replace('.json', '');
        const sessId = parts[parts.length - 2];
        try {
          const resp = await s3.send(new GetObjectCommand({ Bucket: RESULTS_BUCKET, Key: obj.Key }));
          const content = await streamToString(resp.Body);
          const data = JSON.parse(content);
          return {
            job_id: jobId,
            session_id: sessId,
            timestamp: obj.LastModified.toISOString(),
            query_length: data.query_length,
            num_results: data.results?.length ?? data.num_results ?? null,
            top_hit: data.results?.[0]
              ? { target_id: data.results[0].target_id, percent_identity: data.results[0].percent_identity }
              : null,
          };
        } catch {
          return { job_id: jobId, session_id: sessId, timestamp: obj.LastModified.toISOString(), query_length: null, num_results: null, top_hit: null };
        }
      })
    );

    searches.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));
    res.json({ searches, count: searches.length, total: searches.length });

  } catch (err) {
    next(err);
  }
});

export default router;
